const usersData = [
  {id: 0, name: 'John Doe', role: 'Guest', status: 'Pending'},
  {id: 1, name: 'Samppa Nori',  role: 'Member', status: 'Active'},
  {id: 2, name: 'Estavan Lykos', role: 'Staff', status: 'Banned'},
  {id: 3, name: 'Chetan Mohamed', role: 'Admin', status: 'Inactive'},
  {id: 4, name: 'Derick Maximinus', role: 'Member', status: 'Pending'},
  {id: 5, name: 'Friderik Dávid', role: 'Staff', status: 'Active'},
  {id: 6, name: 'Yiorgos Avraamu', role: 'Member', status: 'Active'},
  {id: 7, name: 'Avram Tarasios', role: 'Staff', status: 'Banned'},
  {id: 8, name: 'Quintin Ed', role: 'Admin', status: 'Inactive'},
  {id: 9, name: 'Enéas Kwadwo', role: 'Member', status: 'Pending'},
  {id: 10, name: 'Agapetus Tadeáš', role: 'Staff', status: 'Active'},
  {id: 11, name: 'Carwyn Fachtna', role: 'Member', status: 'Active'},
  {id: 12, name: 'Nehemiah Tatius', role: 'Staff', status: 'Banned'},
  {id: 13, name: 'Ebbe Gemariah', role: 'Admin', status: 'Inactive'},
  {id: 14, name: 'Eustorgios Amulius', role: 'Member', status: 'Pending'},
  {id: 15, name: 'Leopold Gáspár', role: 'Staff', status: 'Active'},
  {id: 16, name: 'Pompeius René', role: 'Member', status: 'Active'},
  {id: 17, name: 'Paĉjo Jadon', role: 'Staff', status: 'Banned'},
  {id: 18, name: 'Micheal Mercurius', role: 'Admin', status: 'Inactive'},
  {id: 19, name: 'Ganesha Dubhghall', role: 'Member', status: 'Pending'},
  {id: 20, name: 'Hiroto Šimun', role: 'Staff', status: 'Active'},
  {id: 21, name: 'Vishnu Serghei', role: 'Member', status: 'Active'},
  {id: 22, name: 'Zbyněk Phoibos', role: 'Staff', status: 'Banned'},
  {id: 23, name: 'Einar Randall', role: 'Admin', status: 'Inactive'},
  {id: 24, name: 'Félix Troels', role: 'Staff', status: 'Active'},
  {id: 25, name: 'Aulus Agmundr', role: 'Member', status: 'Pending'},
  {id: 42, name: 'Ford Prefex', role: 'Alien', status: 'Don\'t panic!'}
]

export default usersData
